### ISSUE TITLE
Support v0.1.0 on Windows

### ISSUE THREAD

**Issue by leofang** [conda-forge/cusparselt-feedstock#10]
See https://github.com/conda-forge/cusparselt-feedstock/pull/9#issuecomment-824815181.

**Comment by mnicely** [comment]
Still need to work this.

**Comment by mnicely** [comment]
@leofang Still working this :disappointed: 

In the meantime, can we update the homepage address? It should be cusparse not cusparselt.

**Comment by leofang** [comment]
> @leofang Still working this 😞

No problem Matt, thanks for keeping me posted!

> In the meantime, can we update the homepage address? It should be cusparse not cusparselt.

@jakirkham Question: If I update `meta.yaml`, will the fix propagate to the `conda-forge` channel? I remember it used to require manual fix (from you 😅) but perhaps Anaconda has fixed it recently?

**Comment by jakirkham** [comment]
In theory updating the recipe should fix it now. If it doesn't, please let me know and I'll work with them on getting it fixed.

**Comment by leofang** [comment]
It's available now: https://developer.download.nvidia.com/compute/cutensor/1.3.0/local_installers/libcusparse_lt-windows-x86_64-0.1.0.2.zip. I'll find some time to add it today or tomorrow.

**Comment by leofang** [comment]
> It's available now: https://developer.download.nvidia.com/compute/cutensor/1.3.0/local_installers/libcusparse_lt-windows-x86_64-0.1.0.2.zip. I'll find some time to add it today or tomorrow.

Hmmm the link is invalid....Maybe I'll wait a bit...

**Comment by mnicely** [comment]
@leofang cutensor shouldn't be in the path. Let me file an issue.

**Comment by leofang** [comment]
https://developer.nvidia.com/compute/libcusparse-lt/0.1.0/local_installers/libcusparse_lt-windows-x86_64-0.1.0.2.zip
