### ISSUE TITLE
License hyperlink on anaconda.org not working

### ISSUE THREAD

**Issue by leofang** [conda-forge/cusparselt-feedstock#14]
This hyperlink on anaconda.org does not correctly jump to `license_url` set in `meta.yaml`:
<img width="740" alt="截圖 2022-01-05 下午3 24 50" src="https://user-images.githubusercontent.com/5534781/148284192-3560e095-59c0-42ee-8429-e085309825d3.png">

**Comment by jakirkham** [comment]
This is similar to the issue we had with `cudatoolkit` ( https://github.com/conda-forge/cudatoolkit-feedstock/issues/2 ), but we fixed that one.

@chenghlee, would you be able to help us here? 🙂

**Comment by leofang** [comment]
Closing, this is fixed now!
