### ISSUE TITLE
How to ship a package for Tegra/Jetson?

### ISSUE THREAD

**Issue by leofang** [conda-forge/cusparselt-feedstock#48]
@kvoronin raised this question offline. Starting v0.6.2 cuSPARSELt supports sm87:
https://docs.nvidia.com/cuda/cusparselt/release_notes.html#cusparselt-v0-6-2

**Comment by kvoronin** [comment]
Per offline discussion, currently the `arm_variant` needs to be extended to support this and since there are no actual requests for getting cusparselt for jetson via conda, for now the jetson package will not be distributed over conda.

**Comment by traversaro** [comment]
Hello @kvoronin @leofang, sorry for commenting on a closed issue. I work at the Italian Institute of Technology (https://www.iit.it), and indeed we tried to use conda-forge CUDA packages on Jetson Orin, and we hit the problem of cublas and cudnn not having `sm_87` architecture (see https://github.com/conda-forge/pytorch-cpu-feedstock/issues/303). We can work on adding the `sm_87` architecture on open source packages (either directly in the recipe or building our own forks), but clearly we can't easily create cudnn and cublas sm_87-enabled packages. 

I guess it would not be sufficient a single "actual requests" from us to convince NVIDIA to allocate work to add `sm_87` architectures to conda-forge's cuda `linux-aarch64`, however I want to ask: what is the correct channel to "actual request" for sm_87-support in conda-forge's CUDA packages? Thanks in advance!

**Comment by kvoronin** [comment]
+ @jakirkham for awareness/discussion. In https://github.com/conda-forge/cuda-feedstock/issues/57 I see references to the drafts for attempts to add a tegra arm variant, will this work (I assume, not, which is the reason we didn't do it for cusparselt and other packages)?

**Comment by jakirkham** [comment]
Thanks Kirill! 🙏

Discussed this with Silvio in this thread: https://github.com/conda-forge/libcublas-feedstock/pull/32#issuecomment-2537155195

After which Silvio opened the `cuda-feedstock` issue that you linked

We can discuss what will be needed to move that forward in our next meeting
